### ISSUE TITLE
Autofill!

### ISSUE THREAD

**Issue by MiguelGrande** [themerekat/CCH2-problems#7]
Although autofill can be useful, I have found it annoying.  It is too "eager" to place text.  I and student assistants have inadvertently added autofill suggestions, sometimes not catching the errors.  (We have had several United Arab Emirite entries in place of United States.)  It either needs to be revised (e.g., with a pull-down menu that you must consciously click), or a toggle set to disengage it.  Other than taxonomic names, which have a pull-down menu, I would prefer to live without it.

**Comment by CCH2-portal** [comment]
This is usually the result of a browser setting rather than CCH2 itself.
